image: nfqsolutions/node:8.15-chrome

stages:
  - build
  - test
  - sonar-scanner

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build-tableau
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run test-ci
    # Add ci script on headless mode

sonar-scanner:
  stage: sonar-scanner
  image: miglesiassarria/sonar-scanner
  script:
    - sonar-scanner -Dsonar.host.url=http://sonar.nfqsolutions.es:9900 -Dsonar.projectKey=ngx-tableau -Dsonar.login=b70ea19b709786345699f67f0d12eabae3e36f1c -Dsonar.sources=projects/tableau/src -Dsonar.exclusions=projects/tableau/src/testAssets/** -Dsonar.ts.tslint.projectPath=projects/tableau/tslint.json -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
